apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: motherhugger-nl-tls
spec:
  secretName: motherhugger-nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: motherhugger.nl
  dnsNames:
    - motherhugger.nl
    - www.motherhugger.nl
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - motherhugger.nl
          - www.motherhugger.nl
